In [1]:
import pandas as pd
import pyodbc
from faker import Faker

In [2]:
for d in pyodbc.drivers():
    print(d)

SQL Server
SQL Server Native Client RDA 11.0
ODBC Driver 17 for SQL Server
Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
Microsoft Access Text Driver (*.txt, *.csv)

In [10]:
conn=pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                    'Server=(local);'
                    'Database=exam_try;'
                    'Trusted_Connection=yes;')
crs=conn.cursor()

#

In [35]:
import pyodbc
from faker import Faker

# Connect to the SQL Server database
connection = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                            'Server=(local);'
                            'Database=Examination System;'
                            'Trusted_Connection=yes;')
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# List of skills
skills_data = [
    "Communication",
    "Critical Thinking",
    "Adaptability",
    "Creativity",
    "Teamwork",
    "Time Management",
    "Leadership",
    "Technical",
    "Emotional Intelligence",
    "Presentation"
]

# Insert fake data into the Skills table
for skill_name in skills_data:
    cursor.execute("INSERT INTO Skills (Skill_Name) VALUES (?)", (skill_name,))
    connection.commit()

# Close the connection
connection.close()

In [36]:
import pyodbc
from faker import Faker
from datetime import datetime, timedelta
import random

# Connect to the SQL Server database
connection = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                            'Server=(local);'
                            'Database=Examination System;'
                            'Trusted_Connection=yes;')
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# List of certificate data (name and random issuer from the specified list)
certificates_data = [
    {"Cert_Name": "Information Technology (IT) Certifications"},
    {"Cert_Name": "Certified ScrumMaster (CSM)"},
    {"Cert_Name": "Registered Nurse (RN)"},
    {"Cert_Name": "Adobe Certified Associate (ACA)"},
    {"Cert_Name": "Certificate in English Language Teaching to Adults (CELTA)"},
    {"Cert_Name": "Teaching English as a Foreign Language (TEFL)"},
    {"Cert_Name": "Certified Pharmacy Technician (CPhT)"},
    {"Cert_Name": "Certified Management Accountant (CMA)"},
    {"Cert_Name": "Cisco Certified Network Associate (CCNA)"},
    {"Cert_Name": "Certified Information Systems Security Professional (CISSP)"},
    {"Cert_Name": "Microsoft Certified: Azure Administrator Associate"},
]

# Insert fake data into the Certificates table
for cert_data in certificates_data:
    # Randomly choose an issuer from the list
    issuer = random.choice(["Coursera", "Udemy", "DataCamp"])
    
    # Generate a random date within the specified range
    start_date = datetime(2022, 1, 2)
    end_date = datetime(2024, 4, 8)
    issue_date = faker.date_time_between_dates(datetime_start=start_date, datetime_end=end_date).date()
    
    cursor.execute("INSERT INTO Certificates (Cert_Name, Issuer, Issue_Date) VALUES (?, ?, ?)",
                   (cert_data["Cert_Name"], issuer, issue_date))
    connection.commit()

# Close the connection
connection.close()

In [37]:
import pyodbc
from faker import Faker

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# List of topic names
topics = [
    "Data Science and Analytics",
    "Programming and Development",
    "System Architecture and Organization",
    "Emerging Technologies",
    "Software Quality and Testing",
    "Human-Computer Interaction and Graphics",
    "Networking and Cloud Computing",
    "Data Science",
    "Mobile App Development",
]

# Insert fake data into the Topic table
for topic in topics:
    cursor.execute("INSERT INTO Topic (Top_Name) VALUES (?)", (topic,))
    connection.commit()

# Close the connection
connection.close()

In [38]:
import pyodbc
from faker import Faker
from datetime import datetime, timedelta

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# List of training names
training_names = [
    "Python Fundamentals",
    "Advanced Python Programming",
    "Data Science with Python",
    "Machine Learning Basics",
    "Web Development Bootcamp",
    "Mobile App Development Workshop",
    "Full-Stack JavaScript",
    "Agile Project Management",
    "Digital Marketing Strategies",
    "Social Media Mastery",
    "Search Engine Optimization (SEO) Essentials",
    "Spanish Language for Beginners",
    "Financial Modeling and Analysis",
    "Investing in Stocks 101",
    "Yoga for Beginners",
    "Graphic Design Principles",
    "3D Animation Workshop",
    "Nutrition and Health Basics",
    "Effective Communication Skills",
    "Leadership Development Program",
    "Cloud Computing Essentials",
    "Cybersecurity Fundamentals",
    "Blockchain Basics",
    "Artificial Intelligence Fundamentals",
    "Ethical Hacking Workshop",
    "Effective Time Management",
    "Customer Service Excellence",
    "Public Speaking Mastery",
    "Problem-Solving Strategies",
    "Emotional Intelligence in the Workplace",
]

# Insert fake data into the Training table
for training_name in training_names:
    start_date = faker.date_between(start_date='-365d', end_date='today')
    end_date = start_date + timedelta(days=faker.random_int(min=7, max=60))  # Random duration between 7 to 60 days
    cursor.execute("INSERT INTO Training (Train_Name, Start_Date, End_Date) VALUES (?, ?, ?)",
                   (training_name, start_date, end_date))
    connection.commit()

# Close the connection
connection.close()

In [39]:
import pyodbc
from faker import Faker

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# List of position names
position_names = [
    "Software Engineer",
    "Data Scientist",
    "Web Developer",
    "Product Manager",
    "UX/UI Designer",
    "Network Engineer",
    "Business Analyst",
    "Digital Marketing Specialist",
    "Project Manager",
    "Financial Analyst",
    "HR Manager",
    "IT Support Specialist",
    "Cybersecurity Analyst",
    "Content Writer",
    "Graphic Designer",
    "DevOps Engineer",
    "Mobile App Developer",
    "Systems Administrator",
    "Sales Manager",
    "Customer Success Representative",
    "Healthcare Administrator",
    "Quality Assurance Tester",
    "Research Scientist",
    "Social Media Manager",
    "Technical Support Engineer",
    "Database Administrator",
    "IT Consultant",
    "Network Security Engineer",
    "Machine Learning Engineer",
    "UI/UX Lead",
    "E-commerce Manager",
    "Technical Project Manager",
    "Cloud Solutions Architect",
    "Financial Planner",
    "Event Coordinator",
    "Public Relations Specialist",
    "Supply Chain Analyst",
    "Environmental Engineer",
    "AI Ethics Specialist",
    "Game Developer",
    "Quantum Computing Researcher",
    "Blockchain Developer",
    "Energy Analyst",
    "Sustainability Coordinator",
    "Foreign Language Translator",
    "Robotics Engineer",
    "Space Scientist",
]

# Insert fake data into the Positions table
for position_name in position_names:
    salary = faker.random_int(min=50000, max=150000)  # Random salary between $50,000 and $150,000
    cursor.execute("INSERT INTO Positions (Position_Name, Salary) VALUES (?, ?)",
                   (position_name, salary))
    connection.commit()

# Close the connection
connection.close()

In [42]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# List of department names
department_names = [
    "Human Resources",
    "Marketing",
    "Finance",
    "Information Technology",
    "Sales",
    "Customer Service",
    "Research and Development",
    "Operations",
    "Legal",
    "Public Relations",
    "Supply Chain",
    "Quality Assurance",
    "Product Management",
    "Administration",
    "Engineering",
    "Training and Development",
    "Health and Safety",
    "Facilities",
    "Business Development",
    "Data Science",
]

# Insert fake data into the Department table
for department_name in department_names:
    # Generate a random location
    dept_location = faker.city()

    # Randomly select a manager from existing instructors
    cursor.execute("SELECT Ins_Id FROM Instructor ORDER BY NEWID()")
    result = cursor.fetchone()
    dept_manager = result[0] if result else None

    # Generate a random hire date
    manager_hiredate = faker.date_between(start_date='-5y', end_date='today')

    cursor.execute("INSERT INTO Department (Dept_Name, Dept_Location, Dept_Manager, Manager_hiredate) VALUES (?, ?, ?, ?)",
                   (department_name, dept_location, dept_manager, manager_hiredate))
    connection.commit()

# Close the connection
connection.close()

In [43]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# Insert fake data into the Instructor table
for _ in range(20):  # Assuming 20 instructors, adjust as needed
    ins_name = faker.name()
    salary = random.randint(50000, 100000)  # Adjust the salary range as needed

    # Generate a random department for the instructor
    cursor.execute("SELECT Dept_Id FROM Department ORDER BY NEWID()")
    result = cursor.fetchone()
    dept_id = result[0] if result else None

    cursor.execute("INSERT INTO Instructor (Ins_Name, Salary, Dept_Id) VALUES (?, ?, ?)",
                   (ins_name, salary, dept_id))
    connection.commit()

# Update the Dept_Manager foreign key in the Department table
cursor.execute("UPDATE Department SET Dept_Manager = Ins_Id FROM Instructor WHERE Department.Dept_Id = Instructor.Dept_Id")
connection.commit()

# Close the connection
connection.close()

In [44]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# Insert fake data into the Companies table
for _ in range(20):  # Assuming 10 companies, adjust as needed
    company_name = faker.company()
    location = faker.city()

    # Generate a random training for the company
    cursor.execute("SELECT Train_ID FROM Training ORDER BY NEWID()")
    result = cursor.fetchone()
    training_id = result[0] if result else None

    cursor.execute("INSERT INTO Companies (Company_Name, Location, Training_ID) VALUES (?, ?, ?)",
                   (company_name, location, training_id))
    connection.commit()

# Close the connection
connection.close()

In [45]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# Insert fake data into the Projects table
for _ in range(10):  # Assuming 10 projects, adjust as needed
    project_name = faker.company()
    start_date = faker.date_between(start_date='-30d', end_date='today')
    end_date = faker.date_between(start_date=start_date, end_date='+30d')

    cursor.execute("INSERT INTO Projects (Project_Name, Start_Date, End_Date) VALUES (?, ?, ?)",
                   (project_name, start_date, end_date))
    connection.commit()

# Close the connection
connection.close()

In [46]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
faker = Faker()

# Course names provided
courses_name = [
    "Software Engineering",
    "Operating Systems",
    "Computer Organization and Architecture",
    "Object-Oriented Programming",
    "Data Structures and Algorithms",
    "Introduction to Programming",
    "Database Management Systems",
    "Web Development",
    "Cybersecurity",
    "Artificial Intelligence",
    "Software Testing",
    "Networking",
    "Mobile App Development",
    "Computer Graphics",
    "Human-Computer Interaction (HCI)",
    "Data Science",
    "Robotics",
    "Quantum Computing",
    "Augmented Reality (AR)",
    "Internet of Things (IoT)",
    "Blockchain Technology",
    "Cloud Computing"
]

# Get the existing topics from the Topic table
cursor.execute("SELECT Top_Id FROM Topic")
topic_ids = [row.Top_Id for row in cursor.fetchall()]

# Insert fake data into the Course table
for course_name in courses_name:
    course_duration = random.randint(1, 12)  # Random duration in months
    random_topic_id = random.choice(topic_ids)

    cursor.execute("INSERT INTO Course (Crs_Name, Crs_Duration, Top_Id) VALUES (?, ?, ?)",
                   (course_name, course_duration, random_topic_id))
    connection.commit()

# Close the connection
connection.close()

In [67]:
import pyodbc
import random
from datetime import datetime, timedelta

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Exam Names
exam_names = [
    "Software Engineering",
    "Operating Systems",
    "Computer Organization and Architecture",
    "Object-Oriented Programming",
    "Data Structures and Algorithms",
    "Introduction to Programming",
    "Database Management Systems",
    "Web Development",
    "Cybersecurity",
    "Artificial Intelligence",
    "Software Testing",
    "Networking",
    "Mobile App Development",
    "Computer Graphics",
    "Human-Computer Interaction (HCI)",
    "Data Science",
    "Robotics",
    "Quantum Computing",
    "Augmented Reality (AR)",
    "Internet of Things (IoT)",
    "Blockchain Technology",
    "Cloud Computing"
]

try:
    # Generate fake data for exams
    for exam_name in exam_names:
        # Remove the word 'Exam' and trim spaces
        exam_name_without_exam = exam_name.replace("Exam", "").strip()

        # Find the corresponding course with the same name
        cursor.execute("SELECT Crs_Id FROM Course WHERE Crs_Name = ?", exam_name_without_exam)
        rows = cursor.fetchall()

        if rows:
            for row in rows:
                crs_id = row.Crs_Id
                num_exams = random.randint(1, 5)  # Random number of exams between 1 and 5

                for _ in range(num_exams):
                    # Generate a random date within the next 30 days
                    exam_date = datetime.now() + timedelta(days=random.randint(1, 30))

                    # Insert into the 'Exam' table
                    cursor.execute("INSERT INTO Exam (Exam_Name, Exam_Date, Crs_Id) VALUES (?, ?, ?)", exam_name, exam_date, crs_id)
        else:
            print(f"No matching course found for exam: {exam_name}. Skipping exam creation.")

    # Commit the changes
    connection.commit()
    print("Data inserted successfully.")
except Exception as e:
    print(f"Error: {e}")
finally:
    # Close the connection
    connection.close()

Data inserted successfully.

#

In [74]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
fake = Faker()

# Fetch the existing Department IDs from the Department table
cursor.execute("SELECT Dept_Id FROM [dbo].[Department]")
dept_ids = [row.Dept_Id for row in cursor.fetchall()]

# Generate fake and random data for the Student table using Faker
for _ in range(250):  # Adjust the range based on the number of students you want to generate
    first_name = fake.first_name()
    last_name = fake.last_name()
    address = fake.address()
    age = random.randint(18, 50)
    email = fake.email()
    dept_id = random.choice(dept_ids)  # Randomly select a department ID
    gender = random.choice(['Male', 'Female'])

    # Insert data into the Student table
    query = f"INSERT INTO [dbo].[Student] ([St_Fname], [St_Lname], [St_Address], [St_Age], [Email], [Dept_Id], [Gender]) " \
            f"VALUES ('{first_name}', '{last_name}', '{address}', {age}, '{email}', {dept_id}, '{gender}')"
    cursor.execute(query)

# Commit the changes and close the connection
connection.commit()
connection.close()

In [75]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Create a Faker instance
fake = Faker()

# Fetch the existing Student IDs from the Student table
cursor.execute("SELECT St_Id FROM [dbo].[Student]")
existing_st_ids = [row.St_Id for row in cursor.fetchall()]

# Shuffle the list of St_Id values
random.shuffle(existing_st_ids)

# Update the st_super column for each St_Id
for st_id in existing_st_ids:
    st_super = random.choice(existing_st_ids)  # Randomly select an existing St_Id
    cursor.execute(f"UPDATE [dbo].[Student] SET [St_super] = {st_super} WHERE [St_Id] = {st_id}")

# Commit the changes and close the connection
connection.commit()
connection.close()

In [80]:
import pyodbc
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Fetch all Student and Exam IDs
cursor.execute("SELECT St_Id FROM [dbo].[Student]")
st_ids = [row.St_Id for row in cursor.fetchall()]

cursor.execute("SELECT Exam_Id FROM [dbo].[Exam]")
exam_ids = [row.Exam_Id for row in cursor.fetchall()]

# Generate random associations in St_Exam table
for st_id in st_ids:
    # Determine the number of exams to assign to each student (e.g., between 1 and 3)
    num_exams = random.randint(1, 3)
    selected_exams = random.sample(exam_ids, min(num_exams, len(exam_ids)))
    
    for exam_id in selected_exams:
        cursor.execute(f"INSERT INTO [dbo].[St_Exam] ([St_Id], [Ex_Id]) VALUES ({st_id}, {exam_id})")

# Commit the changes and close the connection
connection.commit()
connection.close()

# --DBCC CHECKIDENT ('[dbo].[St_Exam]', RESEED, 0);

In [93]:
import pyodbc
import random
from datetime import datetime, timedelta

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Function to get unique non-repeating St_Id values from the Student table
def get_unique_student_ids():
    cursor.execute("SELECT TOP 250 St_Id FROM [dbo].[Student] ORDER BY NEWID()")
    return [row[0] for row in cursor.fetchall()]

# Function to generate random data for the Hiring table
def generate_hiring_data(num_records):
    hiring_data = []
    unique_student_ids = get_unique_student_ids()

    print("Number of Unique Student IDs:", len(unique_student_ids))
    print("Unique Student IDs:", unique_student_ids)

    # Fetching the range of Company_Id values from the Companies table
    cursor.execute("SELECT MIN(Company_Id), MAX(Company_Id) FROM [dbo].[Companies]")
    min_company_id, max_company_id = cursor.fetchone()

    # Fetching the range of Position_Id values from the Positions table
    cursor.execute("SELECT MIN(Position_Id), MAX(Position_Id) FROM [dbo].[Positions]")
    min_position_id, max_position_id = cursor.fetchone()

    for _ in range(num_records):
        # Check if there are enough unique student IDs
        if not unique_student_ids:
            break

        company_id = random.randint(min_company_id, max_company_id)  # Using the valid range
        position_id = random.randint(min_position_id, max_position_id)  # Using the valid range
        st_id = unique_student_ids.pop(0)  # Get a unique St_Id
        hire_date = datetime.now() - timedelta(days=random.randint(1, 365))  # Random hire date in the last year
        contract_length = random.randint(1, 12)  # Assuming contract length in months

        hiring_data.append((company_id, position_id, st_id, hire_date.date(), contract_length))

    return hiring_data

# Generate fake data for the Hiring table
num_records = 125  # Adjust the number of records as needed
hiring_data = generate_hiring_data(num_records)

# Insert fake data into the Hiring table
cursor.executemany("INSERT INTO [dbo].[Hiring] (Company_Id, Position_Id, St_Id, Hire_Date, ContractLength) "
                   "VALUES (?, ?, ?, ?, ?)", hiring_data)

# Commit the changes
connection.commit()

# Close the connection
connection.close()

Number of Unique Student IDs: 250
Unique Student IDs: [111, 330, 276, 275, 278, 159, 218, 238, 129, 307, 197, 287, 288, 222, 122, 133, 116, 183, 211, 260, 219, 254, 114, 198, 256, 144, 195, 352, 267, 235, 225, 280, 154, 118, 314, 173, 336, 169, 136, 120, 178, 210, 339, 209, 140, 332, 191, 151, 213, 168, 285, 245, 157, 233, 187, 300, 158, 350, 249, 274, 216, 303, 315, 258, 152, 304, 137, 132, 112, 146, 221, 297, 175, 320, 246, 327, 342, 290, 179, 240, 164, 348, 131, 312, 201, 149, 317, 223, 117, 313, 172, 142, 324, 277, 283, 291, 107, 141, 127, 237, 156, 220, 200, 340, 252, 231, 232, 188, 261, 186, 166, 338, 343, 345, 130, 253, 281, 145, 263, 331, 309, 306, 262, 202, 177, 180, 110, 273, 244, 155, 192, 257, 319, 203, 292, 189, 229, 326, 153, 294, 113, 305, 299, 282, 230, 139, 204, 181, 337, 109, 176, 296, 354, 226, 318, 329, 301, 126, 207, 199, 148, 323, 135, 121, 105, 311, 167, 289, 134, 165, 228, 194, 208, 353, 185, 328, 284, 264, 298, 346, 239, 224, 128, 123, 341, 310, 286, 265, 206, 124, 308, 295, 115, 250, 316, 227, 333, 242, 162, 236, 125, 347, 217, 212, 170, 269, 270, 184, 106, 322, 160, 255, 190, 268, 214, 334, 182, 119, 150, 108, 171, 325, 205, 161, 163, 247, 215, 193, 279, 351, 321, 243, 259, 293, 251, 266, 138, 271, 143, 248, 272, 234, 335, 174, 349, 196, 241, 344, 302, 147]

In [9]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Get a list of existing Ins_Id and Crs_Id values from Instructor and Course tables
cursor.execute("SELECT Ins_Id FROM [dbo].[Instructor];")
existing_ins_ids = [row.Ins_Id for row in cursor.fetchall()]

cursor.execute("SELECT Crs_Id FROM [dbo].[Course];")
existing_crs_ids = [row.Crs_Id for row in cursor.fetchall()]

# Generate fake data for Instructor_course table
num_records = 100  # You can adjust this based on your needs
instructor_course_data = []

fake = Faker()
evaluations = ['Excellent', 'Good', 'Very Good', 'Fair']

for _ in range(num_records):
    ins_id = random.choice(existing_ins_ids)
    crs_id = random.choice(existing_crs_ids)
    evaluation = random.choice(evaluations)
    
    instructor_course_data.append((ins_id, crs_id, evaluation))

# Insert fake data into the Instructor_course table
cursor.executemany("INSERT INTO [dbo].[Instructor_course] (Ins_Id, Crs_Id, Evaluation) VALUES (?, ?, ?)", instructor_course_data)

# Commit the changes
connection.commit()

# Close the connection
connection.close()

In [4]:
import pyodbc
import random
from datetime import datetime, timedelta

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Get a list of existing St_Id and Cert_Id values from Student and Certificates tables
cursor.execute("SELECT St_Id FROM [dbo].[Student];")
existing_st_ids = [row.St_Id for row in cursor.fetchall()]

cursor.execute("SELECT Cert_Id FROM [dbo].[Certificates];")
existing_cert_ids = [row.Cert_Id for row in cursor.fetchall()]

# Generate random data for Student_Certificates table
num_records = 100  # You can adjust this based on your needs
student_certificates_data = []

for _ in range(num_records):
    st_id = random.choice(existing_st_ids)
    cert_id = random.choice(existing_cert_ids)
    
    student_certificates_data.append((st_id, cert_id))

# Insert fake data into the Student_Certificates table
cursor.executemany("INSERT INTO [dbo].[Student_Certificates] (St_Id, Cert_Id) VALUES (?, ?)", student_certificates_data)

# Commit the changes
connection.commit()

# Close the connection
connection.close()

In [10]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Get a list of existing St_Id and Crs_Id values from Student and Course tables
cursor.execute("SELECT St_Id FROM [dbo].[Student];")
existing_st_ids = [row.St_Id for row in cursor.fetchall()]

cursor.execute("SELECT Crs_Id FROM [dbo].[Course];")
existing_crs_ids = [row.Crs_Id for row in cursor.fetchall()]

# Generate fake data for Student_course table with grade numbers between 20 and 100
num_records = 300  # You can adjust this based on your needs
student_course_data = []

fake = Faker()

for _ in range(num_records):
    st_id = random.choice(existing_st_ids)
    crs_id = random.choice(existing_crs_ids)
    grade = random.randint(20, 100)
    
    student_course_data.append((crs_id, st_id, grade))

# Insert fake data into the Student_course table
cursor.executemany("INSERT INTO [dbo].[Student_course] (Crs_Id, St_Id, Grade) VALUES (?, ?, ?)", student_course_data)

# Commit the changes
connection.commit()

# Close the connection
connection.close()

In [11]:
import pyodbc
from faker import Faker
import random

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Get a list of existing St_Id and Pro_Id values from Student and Projects tables
cursor.execute("SELECT St_Id FROM [dbo].[Student];")
existing_st_ids = [row.St_Id for row in cursor.fetchall()]

cursor.execute("SELECT Project_Id FROM [dbo].[Projects];")
existing_pro_ids = [row.Project_Id for row in cursor.fetchall()]

# Generate fake data for Student_Project table
num_records = 250  # You can adjust this based on your needs
student_project_data = []

fake = Faker()

for _ in range(num_records):
    st_id = random.choice(existing_st_ids)
    pro_id = random.choice(existing_pro_ids)
    
    student_project_data.append((st_id, pro_id))

# Insert fake data into the Student_Project table
cursor.executemany("INSERT INTO [dbo].[Student_Project] (St_Id, Pro_Id) VALUES (?, ?)", student_project_data)

# Commit the changes
connection.commit()

# Close the connection
connection.close()

In [12]:
import pyodbc
from faker import Faker

# Connect to the SQL Server database
connection_string = 'Driver={ODBC Driver 17 for SQL Server};Server=(local);Database=Examination System;Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()

# Get a list of all existing St_Id and Sk_Id values from Student and Skills tables
cursor.execute("SELECT St_Id FROM [dbo].[Student];")
all_st_ids = [row.St_Id for row in cursor.fetchall()]

cursor.execute("SELECT Skill_Id FROM [dbo].[Skills];")
existing_sk_ids = [row.Skill_Id for row in cursor.fetchall()]

# Generate fake data for Student_skills table
student_skills_data = []

fake = Faker()

for st_id in all_st_ids:
    sk_id = random.choice(existing_sk_ids)  # Adjust this line if you want to select a specific Skill_Id or generate them differently
    
    student_skills_data.append((sk_id, st_id))

# Insert fake data into the Student_skills table
cursor.executemany("INSERT INTO [dbo].[Student_skills] (Sk_Id, St_Id) VALUES (?, ?)", student_skills_data)

# Commit the changes
connection.commit()

# Close the connection
connection.close()

In [34]:
import pyodbc

# Connect to the SQL Server database
connection = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                            'Server=(local);'
                            'Database=Examination System;'
                            'Trusted_Connection=yes;')

# Create a cursor
cursor = connection.cursor()

try:
    # Disable foreign key checks
    cursor.execute("EXEC sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'")

    # Delete all data from all tables
    cursor.execute("EXEC sp_MSforeachtable 'DELETE FROM ?'")

    # Re-enable foreign key checks
    cursor.execute("EXEC sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'")

    # Commit the transaction
    connection.commit()

    print("All data deleted successfully.")
except Exception as e:
    # Rollback the transaction if an error occurs
    connection.rollback()
    print(f"Error: {e}")
finally:
    # Close the cursor and connection
    cursor.close()
    connection.close()

All data deleted successfully.